---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-master
  namespace: system-upgrade
spec:
  concurrency: 1
  version: v1.17.3+k3s1
  nodeSelector:
    matchLabels:
      node.kubernetes.io/instance-type: k3s
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: node-role.kubernetes.io/master, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  cordon: true
#  drain:
#    force: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-worker
  namespace: system-upgrade
spec:
  concurrency: 2
  version: v1.17.3+k3s1
  nodeSelector:
    matchLabels:
      node.kubernetes.io/instance-type: k3s
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: node-role.kubernetes.io/master, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade:v1.17.3-k3s1
    args: ["prepare", "k3s-master"]
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
