# Runs end-to-end test
name: E2E Test
on:
    push:
    workflow_dispatch:
jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: "1.20"
        - name: Run tests
          run: |
            curl -sL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2; \
            curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.3/kustomize_v5.0.3_linux_amd64.tar.gz" | tar -xz -C /usr/local/bin; \
            curl -sL "https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/sonobuoy_${SONOBUOY_VERSION}_linux_${ARCH}.tar.gz" | tar -xz -C /usr/local/bin; \
            curl -sL "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose && \
            chmod +x /usr/local/bin/docker-compose; \
            mkdir -p /usr/local/lib/docker/cli-plugins; \
            export KUBECONFIG /root/.kube/config
            export KUBEHOST 172.17.0.1
            export SONOBUOY_VERSION=0.56.16 \
            curl -o /usr/local/lib/docker/cli-plugins/docker-buildx -fsSL "https://github.com/docker/buildx/releases/download/v0.11.2/buildx-v0.11.2.linux-${ARCH}"; \
            chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx; \
            ./scripts/build; \
            ./scripts/package

