# Responsible for building and testing the application's Go code.
# Runs: build, test, lint
name: Golang Build and Unit Tests
on:
    push:
    workflow_dispatch:
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test Container Package
        run: go test -v -timeout 30s github.com/rancher/system-upgrade-controller/pkg/upgrade/container 

      - name: Test Job Package
        run: go test -v -timeout 30s github.com/rancher/system-upgrade-controller/pkg/upgrade/job 
      - name: Test Node Package
        run: go test -v -timeout 30s github.com/rancher/system-upgrade-controller/pkg/upgrade/node 
      - name: Test Plan Package
        run: go test -v -timeout 30s github.com/rancher/system-upgrade-controller/pkg/upgrade/plan 

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2